version: '3.8'

services:
  db:
    image: postgres:15
    container_name: strava_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strava
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/strava
      - STRAVA_CLIENT_ID=your_id
      - STRAVA_CLIENT_SECRET=your_secret
      - STRAVA_REDIRECT_URI=http://localhost:4000/auth/callback
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  pgdata:
